- name: Ensure cache is up-to-date
  apt:
    update-cache: yes

- name: Ensure required packages are installed
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Ensure postgresql server is running
  service:
    name: postgresql
    state: started
