- name: Updating apt cache
  apt:
    update_cache: yes

- name: Installing nginx
  apt:
    name: nginx
    state: latest

- name: Starting nginx
  service:
    name: nginx
    state: started

- name: Ensure logging capabilities
  file:
    path: /var/log/nginx/oscmt.bifroe.st/logs/
    state: directory
    mode: 0755
