---
- name: Ensure oscmt is absent
  file:
    path: "{{ userpath }}/oscmt"
    state: absent

- name: Ensure everybody has write access to "{{ userpath }}"
  file:
    path: "{{ userpath }}"
    state: directory
    mode: 0777
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Copy OSCMT to the remote server
  become: no
  synchronize:
    src: ../../../oscmt
    dest: "{{ userpath }}"
    rsync_opts:
      - "--exclude=ansible-playbooks"
      - "--exclude=.git"
      - "--exclude=.gitignore"
      - "--exclude=README.md"
      - "--exclude=uwsgi/uwsgi"

- name: Create a directory for the virtual env
  file:
    path: "{{ venv }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Set up a virtual environment with pip
  become: yes
  pip:
    requirements: "{{ userpath }}/oscmt/requirements.txt"
    virtualenv: "{{ venv }}"
    virtualenv_command: python3-virtualenv
    #virtualenv_python: python3 # only in ansible 2.0++

- name: Migrate Django's database
  django_manage:
    app_path: "{{ userpath }}/oscmt/oscmt/"
    apps: casetool
    command: migrate
    virtualenv: "{{ venv }}"

- name: Collect Django's static files
  django_manage:
    app_path: "{{ userpath }}/oscmt/oscmt/"
    command: collectstatic
    virtualenv: "{{ venv }}"

- name: Ensure write access to "{{ userpath }}" is reduced to the owner
  file:
    path: "{{ userpath }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Change ownership
  file:
    owner: "{{ username }}"
    group: "{{ groupname }}"
    recurse: yes
    path: "{{ userpath }}"
