# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 16:02
from __future__ import unicode_literals

import casetool.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
                ('consecutive_number', models.PositiveIntegerField(default=casetool.models.Case.consecutive_number_generator)),
                ('additional_info', models.CharField(blank=True, max_length=500)),
                ('analysis_storage', models.CharField(blank=True, max_length=256)),
                ('case_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deletion_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseConsultantMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseContactMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Case')),
            ],
        ),
        migrations.CreateModel(
            name='ChainOfCustodyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('handover_by', models.CharField(max_length=200)),
                ('received_by', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('additional_info', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('comments', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cost_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('time_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('nda', models.FileField(blank=True, upload_to=casetool.models.Contract.nda_path, validators=[casetool.models.Contract.validate_file_extension])),
                ('crm_number', models.CharField(blank=True, default='No entry specified', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.FileField(upload_to=casetool.models.Documentation.doc_path, validators=[casetool.models.Documentation.validate_file_extension])),
                ('change_date', models.DateField()),
                ('status', models.CharField(choices=[('DRA', 'draft'), ('REV', 'revision'), ('ACC', 'accepted')], default='DRA', max_length=3)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('producer', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('pictures', models.ImageField(blank=True, upload_to='')),
                ('evidence_type', models.CharField(choices=[('PHY', 'physical'), ('LOG', 'logical'), ('OTH', 'other')], max_length=3)),
                ('isActive', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('seal_type', models.CharField(choices=[('BAG', 'bag'), ('STI', 'sticker')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SubEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('WOR', 'working copy'), ('BES', 'best evidence')], max_length=3)),
                ('parent_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Evidence')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casetool.Seal')),
            ],
        ),
        migrations.AddField(
            model_name='chainofcustodyevent',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Evidence'),
        ),
        migrations.AddField(
            model_name='chainofcustodyevent',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Seal'),
        ),
        migrations.AddField(
            model_name='casecontactmap',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Contact'),
        ),
        migrations.AddField(
            model_name='caseconsultantmap',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Consultant'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Client'),
        ),
        migrations.AddField(
            model_name='case',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Contract'),
        ),
        migrations.AddField(
            model_name='case',
            name='documentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casetool.Documentation'),
        ),
        migrations.AddField(
            model_name='case',
            name='external_main_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='internal_main_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casetool.Consultant'),
        ),
    ]
