# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casetool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': 'Evidence Item', 'verbose_name_plural': 'Evidence Items'},
        ),
        migrations.AlterModelOptions(
            name='subevidence',
            options={'verbose_name': 'SubEvidence Item', 'verbose_name_plural': 'SubEvidence Items'},
        ),
    ]
