---
- hosts: oscmt
  become: yes
  become_method: sudo
  tasks:
        - name: Ensure Python 3.4 is installed and the latest version
          apt:
            pkg: python3.4
            state: latest
          register: python_installation

        - name: Ensure python3-pip is installed and the latest version
          apt:
            pkg: python3-pip
            state: latest
          when: python_installation|success
          register: pip_installation

        - name: Ensure nginx is installed and the latest version
          apt:
            pkg: nginx
            state: latest
          register: nginx_installation

        - name: Ensure letsencrypt is installed and working
          register: letsencrypt_installation

        - name: Configure the webserver
          shell:
          when: nginx_installation|success

        - name: Ensure the required packages for oscmt are installed
          shell:
            pip install -r ../requirements.txt
          when: pip_installation|success
