- hosts: oscmt
  become: yes
  become_method: sudo
  - tasks:
    - name: Ensure cache is up-to-date
      apt:
        update-cache: yes

    - name: Ensure required packages are installed
      apt:
        name: {{item}}
      with_items:
        - postgresql
        - libpq-dev
        - python-pycopg2

- hosts: oscmt
  become: yes
  become_user: postgres

  vars:
    dbname: oscmt
    dbuser: oscmt_user
    dbpassword: 5796f702e10ddb5bd73c70e530bb6b99 # make sure to change that.

  tasks:
    - name: Ensure that database is created
      postgresql_db: 
        name: {{dbname}}

    - name: Ensure user has access to database
      postgresql_user:
        db: {{dbname}}
        name: {{dbuser}}
        passwod: {{dbpassword}}
        priv: ALL

    - name: Ensure user does not have unnecessary privilege
      postgresql_user:
        name: {{dbuser}}
        role_attr_flags: NOSUPERUSER,NOCREATEDB # for tests: NOSUPERUSER only.

    - name: Ensure no other user can access the database
      postgresql_privs:
        db: {{dbname}}
        role: PUBLIC
        type: DATABASE
        priv: ALL
        state: absent
