---
- name: Prepare for logs
  file:
    path: /var/log/uwsgi
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0755

- name: Starting uwsgi
  become: yes
  become_user: "{{ username }}"
  shell:
    "{{ venv }}/bin/uwsgi --ini {{ userpath }}/oscmt/oscmt/oscmt/uwsgi/oscmt.ini"
  args:
    executable: /bin/bash
