---
- name: Ensure uwsgi is installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes

  with_items:
    - uwsgi-emperor
    - uwsgi
    - uwsgi-plugin-python3

- name: Link uwsgi-ini into vassals directory
  file:
    src: /var/www/oscmt/oscmt/uwsgi/oscmt.ini
    dest: /etc/uwsgi-emperor/vassals/oscmt.ini
    state: link

- name: Start uwsgi service
  service:
    name: uwsgi
    state: started
    enabled: yes
