---
- hosts: oscmt
  become: yes
  become_method: sudo

  vars:
    remoteuser: damait06
    username: www-data
    groupname: www-data
    userpath: /var/www
    public_key: ~/.ssh/oscmt.pub
    fqdn: 'oscmt.bifroe.st'
    allowed_hosts: "{{ fqdn }}"
    keyfile: 'oscmt.bifroe.st.key' # ssl-cert keyfile
    certfile: 'oscmt.bifroe.st.crt' # ssl-cert
    dbname: 'oscmt'
    dbuser: 'oscmt_user'
    dbpassword: 'random_string' # make sure to change that.
    secret_key: 'random_string' # make sure to change that.
    venv: "{{ userpath }}/env/oscmt_env"
  

  roles:
    - common
    - ntp
    - ufw
    - ssh
    - python
    - nginx
    - postgresql
    - oscmt
    - uwsgi
