---
- hosts: oscmt
  become: yes
  become_method: sudo

  vars:
    remoteuser: damait06
    username: www-data
    groupname: www-data
    userpath: /var/www
    public_key: ~/.ssh/oscmt.pub
    dbname: 'oscmt'
    dbuser: 'oscmt_user'
    dbpassword: '5796f702e10ddb5bd73c70e530bb6b99' # make sure to change that.
    venv: "{{ userpath }}/env/oscmt_env"
  

  roles:
    - common
    - ntp
    - ufw
    - ssh
    - python
    - nginx
    - postgresql
    - oscmt
    - uwsgi
